# Generated by Django 4.0.2 on 2022-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default=0, max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(default=0, max_length=12, verbose_name='Telephone'),
            preserve_default=False,
        ),
    ]
