# Generated by Django 3.2.4 on 2022-02-13 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case',
        ),
        migrations.AddField(
            model_name='task',
            name='dateTask',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Booking date'),
            preserve_default=False,
        ),
    ]
