# Generated by Django 3.2.4 on 2022-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220213_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTask',
            field=models.CharField(max_length=10, verbose_name='Booking date'),
        ),
    ]
